export { default as SearchOutlined } from '@ant-design/icons/SearchOutlined'
export { default as PlusOutlined } from '@ant-design/icons/PlusOutlined'
export { default as DeleteOutlined } from '@ant-design/icons/DeleteOutlined'
export { default as EditOutlined } from '@ant-design/icons/EditOutlined'
export { default as StopFilled } from '@ant-design/icons/StopFilled'